### ISSUE TITLE
Multi-person Question

### ISSUE THREAD

**Issue by dihuangcode** [XiaoCode-er/Two-Stream-CNN#2]
Thanks for your amazing work!
Here comes one question: in NTU, some videos contain only one person, but some may contain two or more persons. So I am confused about how you solve this.
I read your code, which shows you only solve two-person situation. Am I right?

**Comment by XiaoCode-er** [comment]
If some videos contain only one person, you can construct another person with padding zero. This operating had processed in hdf5 file. 
This model is shared for every input，so extract the feature from conv part and then fuse multi-person feature.

**Comment by dihuangcode** [comment]
thanks a lot! @XiaoCode-er 
I find in some videos(e.g. S015C001P025R002A059_rgb.avi), the body count is wrong(should be 2 but 3). How do you solve this problem?

**Comment by XiaoCode-er** [comment]
@Yedis  You can refer to the link https://github.com/InwoongLee/TS-LSTM and you will know how to process this problem.

**Comment by dihuangcode** [comment]
Thanks a lot!
