### ISSUE TITLE
Data normalization and BN layer

### ISSUE THREAD

**Issue by dihuangcode** [XiaoCode-er/Two-Stream-CNN#4]
Hi, thx for your outstanding work!
I notice that there is no data normalization in your code
and there is no bn layers, too.
Could you explain it?
:)

**Comment by dihuangcode** [comment]
> Hi, thx for your outstanding work!
> I notice that there is no data normalization in your code
> and there is no bn layers, too.
> Could you explain it?
> :)

@XiaoCode-er

**Comment by XiaoCode-er** [comment]
I referred the paper to reproduce this code, in which there is no  data normalization and BN layer.
